# Generated by Django 6.1 on 2026-08-11 21:55

import blog.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                (
                    'description',
                    models.CharField(blank=True, max_length=180),
                ),
            ],
            options={
                'verbose_name_plural': 'blog categories',
                'ordering': ('name',),
                'constraints': [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower('slug'),
                        name='blog_category_slug_ci_uniq',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower('slug'),
                        name='blog_tag_slug_ci_uniq',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.CharField(max_length=360)),
                (
                    'content',
                    models.TextField(
                        help_text=(
                            'Markdown only. Raw HTML is not accepted.'
                        ),
                        validators=[
                            django.core.validators.MaxLengthValidator(100000),
                            blog.validators.validate_markdown_content,
                        ],
                    ),
                ),
                ('cover_image_url', models.URLField(max_length=1000)),
                ('cover_image_alt', models.CharField(max_length=180)),
                (
                    'cover_image_caption',
                    models.CharField(blank=True, max_length=240),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('published', 'Published'),
                            ('archived', 'Archived'),
                        ],
                        db_index=True,
                        default='draft',
                        max_length=12,
                    ),
                ),
                (
                    'is_featured',
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    'published_at',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                (
                    'meta_description',
                    models.CharField(blank=True, max_length=160),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'author',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='blog_posts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='posts',
                        to='blog.blogcategory',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        blank=True,
                        related_name='posts',
                        to='blog.blogtag',
                    ),
                ),
            ],
            options={
                'ordering': ('-published_at', '-created_at', '-id'),
                'indexes': [
                    models.Index(
                        fields=['status', '-published_at'],
                        name='blog_post_status_pub',
                    ),
                    models.Index(
                        fields=['category', '-published_at'],
                        name='blog_post_cat_pub',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower('slug'),
                        name='blog_post_slug_ci_uniq',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('status', 'published'), _negated=True),
                            ('published_at__isnull', False),
                            _connector='OR',
                        ),
                        name='blog_post_published_at_req',
                    ),
                ],
            },
        ),
    ]
