# Generated by Django 6.1 on 2026-08-12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostView',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'visitor_hash',
                    models.CharField(db_index=True, max_length=64),
                ),
                (
                    'viewed_at',
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    'post',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='views',
                        to='blog.blogpost',
                    ),
                ),
            ],
            options={
                'ordering': ('-viewed_at', '-id'),
                'indexes': [
                    models.Index(
                        fields=['post', '-viewed_at'],
                        name='blog_view_post_viewed',
                    ),
                    models.Index(
                        fields=['post', 'visitor_hash', '-viewed_at'],
                        name='blog_view_post_visitor',
                    ),
                ],
            },
        ),
    ]
