# Generated by Django 5.0 on 2024-06-19 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_submitcv"),
    ]

    operations = [
        migrations.AddField(
            model_name="submitcv",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="submitcv",
            name="cover_letter",
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name="submitcv",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
