# Generated by Django 6.1 on 2026-08-09 05:56

import decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_flightbooking_guest_fields_and_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TravelPricingSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('usd_to_ngn_rate', models.DecimalField(decimal_places=4, default='1600.0000', help_text='How many Nigerian naira equal one US dollar.', max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.0001'))])),
                ('flight_markup_percent', models.DecimalField(decimal_places=2, default='0.00', max_digits=6, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.00')), django.core.validators.MaxValueValidator(decimal.Decimal('100.00'))])),
                ('hotel_markup_percent', models.DecimalField(decimal_places=2, default='0.00', max_digits=6, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.00')), django.core.validators.MaxValueValidator(decimal.Decimal('100.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_pricing_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'travel pricing settings',
                'verbose_name_plural': 'travel pricing settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('usd_to_ngn_rate__gt', 0)), name='travel_pricing_positive_usd_ngn_rate'), models.CheckConstraint(condition=models.Q(('flight_markup_percent__gte', 0), ('flight_markup_percent__lte', 100)), name='travel_pricing_valid_flight_markup'), models.CheckConstraint(condition=models.Q(('hotel_markup_percent__gte', 0), ('hotel_markup_percent__lte', 100)), name='travel_pricing_valid_hotel_markup')],
            },
        ),
        migrations.CreateModel(
            name='TravelSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel')], db_index=True, max_length=10)),
                ('criteria', models.JSONField(default=dict)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('display_currency', models.CharField(blank=True, max_length=3)),
                ('minimum_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('maximum_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('client_ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['service_type', '-created_at'], name='trv_search_service_created'), models.Index(fields=['status', '-created_at'], name='trv_search_status_created')],
            },
        ),
    ]
