# Generated by Django 6.1 on 2026-08-09

import decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_travel_admin_pricing_and_search_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelListing',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(db_index=True, max_length=100)),
                (
                    'country',
                    models.CharField(default='Nigeria', max_length=100),
                ),
                ('address', models.CharField(blank=True, max_length=255)),
                ('room_type', models.CharField(max_length=100)),
                (
                    'nightly_amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                decimal.Decimal('0.01')
                            )
                        ],
                    ),
                ),
                (
                    'source_currency',
                    models.CharField(
                        choices=[
                            ('USD', 'US dollar'),
                            ('NGN', 'Nigerian naira'),
                        ],
                        default='NGN',
                        max_length=3,
                    ),
                ),
                (
                    'max_guests',
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    'star_rating',
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ('image_url', models.URLField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                (
                    'available_rooms',
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(100)
                        ],
                    ),
                ),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('test_data', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('city', 'name', 'room_type', 'id'),
                'indexes': [
                    models.Index(
                        fields=['city', 'active'],
                        name='hotel_listing_city_active',
                    )
                ],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('nightly_amount__gt', 0)),
                        name='hotel_lst_price_gt_zero',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('max_guests__gte', 1),
                            ('max_guests__lte', 20),
                        ),
                        name='hotel_lst_guests_range',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('star_rating__gte', 1),
                            ('star_rating__lte', 5),
                        ),
                        name='hotel_lst_stars_range',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('available_rooms__lte', 100)),
                        name='hotel_lst_rooms_range',
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='listing',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='hotel_requests',
                to='base.hotellisting',
            ),
        ),
    ]
