# Generated by Django 6.1 on 2026-08-09

import decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_hotel_listing_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpricingsettings',
            name='flight_markup_fixed_ngn',
            field=models.DecimalField(
                decimal_places=2,
                default='0.00',
                help_text=(
                    'Fixed naira amount added once to the whole itinerary total.'
                ),
                max_digits=14,
                validators=[
                    django.core.validators.MinValueValidator(
                        decimal.Decimal('0.00')
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name='travelpricingsettings',
            name='flight_markup_mode',
            field=models.CharField(
                choices=[
                    ('percentage', 'Percentage'),
                    ('fixed', 'Fixed NGN amount'),
                ],
                default='percentage',
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name='travelpricingsettings',
            name='hotel_markup_fixed_ngn',
            field=models.DecimalField(
                decimal_places=2,
                default='0.00',
                help_text='Fixed naira amount added once to the whole stay total.',
                max_digits=14,
                validators=[
                    django.core.validators.MinValueValidator(
                        decimal.Decimal('0.00')
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name='travelpricingsettings',
            name='hotel_markup_mode',
            field=models.CharField(
                choices=[
                    ('percentage', 'Percentage'),
                    ('fixed', 'Fixed NGN amount'),
                ],
                default='percentage',
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name='travelpricingsettings',
            constraint=models.CheckConstraint(
                condition=models.Q(('flight_markup_fixed_ngn__gte', 0)),
                name='trv_price_flight_fixed_nonneg',
            ),
        ),
        migrations.AddConstraint(
            model_name='travelpricingsettings',
            constraint=models.CheckConstraint(
                condition=models.Q(('hotel_markup_fixed_ngn__gte', 0)),
                name='trv_price_hotel_fixed_nonneg',
            ),
        ),
        migrations.AddConstraint(
            model_name='travelpricingsettings',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('flight_markup_mode__in', ('percentage', 'fixed'))
                ),
                name='trv_price_flight_mode_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='travelpricingsettings',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('hotel_markup_mode__in', ('percentage', 'fixed'))
                ),
                name='trv_price_hotel_mode_valid',
            ),
        ),
    ]
