from django.urls import path
from .views import (
    ReportClaim,
    ContactMail,
    NewsletterSubscription,
    SubmitCv,
    RegisterUser,
    UserProfileAPIView,
    FlightBookingAPIView,
    FlightLocationAPIView,
    FlightSearchAPIView,
    HotelBookingAPIView,
    HotelLocationAPIView,
    HotelSearchAPIView,
    ChatbotAPIView,
    TravelAdminFlightRequestDetailAPIView,
    TravelAdminFlightRequestListAPIView,
    TravelAdminFlightSearchListAPIView,
    TravelAdminHotelRequestDetailAPIView,
    TravelAdminHotelRequestListAPIView,
    TravelAdminHotelListingDetailAPIView,
    TravelAdminHotelListingListAPIView,
    TravelAdminHotelSearchListAPIView,
    TravelAdminOverviewAPIView,
    TravelAdminUserListAPIView,
    TravelAdminUserRoleAPIView,
    TravelPricingSettingsAPIView,
)

urlpatterns = [
    path('chatbot/', ChatbotAPIView.as_view(), name='chatbot'),
    path("report-claim/", ReportClaim.as_view(), name="report-claim"),
    path('contact/', ContactMail.as_view(), name='contact'),
    path('newsletter/', NewsletterSubscription.as_view(), name='newsletter-subscribe'),
    path('submit-cv/', SubmitCv.as_view(), name='submit_cv'),
    path('users/', RegisterUser.as_view(), name='register'),
    path('profile/', UserProfileAPIView.as_view(), name='profile'),
    path('flight-locations/', FlightLocationAPIView.as_view(), name='flight-locations'),
    path('flight-search/', FlightSearchAPIView.as_view(), name='flight-search'),
    path('flight-bookings/', FlightBookingAPIView.as_view(), name='flight-bookings'),
    path('hotel-search/', HotelSearchAPIView.as_view(), name='hotel-search'),
    path('hotel-locations/', HotelLocationAPIView.as_view(), name='hotel-locations'),
    path('hotel-bookings/', HotelBookingAPIView.as_view(), name='hotel-bookings'),
    path(
        'travel-admin/overview/',
        TravelAdminOverviewAPIView.as_view(),
        name='travel-admin-overview',
    ),
    path(
        'travel-admin/settings/',
        TravelPricingSettingsAPIView.as_view(),
        name='travel-admin-settings',
    ),
    path(
        'travel-admin/users/',
        TravelAdminUserListAPIView.as_view(),
        name='travel-admin-users',
    ),
    path(
        'travel-admin/users/<int:pk>/',
        TravelAdminUserRoleAPIView.as_view(),
        name='travel-admin-user-role',
    ),
    path(
        'travel-admin/flight-searches/',
        TravelAdminFlightSearchListAPIView.as_view(),
        name='travel-admin-flight-searches',
    ),
    path(
        'travel-admin/hotels/',
        TravelAdminHotelListingListAPIView.as_view(),
        name='travel-admin-hotels',
    ),
    path(
        'travel-admin/hotels/<int:pk>/',
        TravelAdminHotelListingDetailAPIView.as_view(),
        name='travel-admin-hotel-detail',
    ),
    path(
        'travel-admin/hotel-searches/',
        TravelAdminHotelSearchListAPIView.as_view(),
        name='travel-admin-hotel-searches',
    ),
    path(
        'travel-admin/flight-requests/',
        TravelAdminFlightRequestListAPIView.as_view(),
        name='travel-admin-flight-requests',
    ),
    path(
        'travel-admin/flight-requests/<int:pk>/',
        TravelAdminFlightRequestDetailAPIView.as_view(),
        name='travel-admin-flight-request-detail',
    ),
    path(
        'travel-admin/hotel-requests/',
        TravelAdminHotelRequestListAPIView.as_view(),
        name='travel-admin-hotel-requests',
    ),
    path(
        'travel-admin/hotel-requests/<int:pk>/',
        TravelAdminHotelRequestDetailAPIView.as_view(),
        name='travel-admin-hotel-request-detail',
    ),
]
